services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - microservices_network

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - microservices_network

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
